#define _CONTENT_TYPE "Content-Type: "
#define _CONTENT_LENGTH "Content-Length: "
#define _BAD_REQUEST "bad request"
#define _OK "OK"
#define _NOT_FOUND "Not found"
#define _TEXT_HTML "text/html"
#define _TEXT_JS "text/javascript"
#define _TEXT_CSS "text/css"
#define _IMAGE_X_ICON "image/x-icon"
#define _IMAGE_PNG "image/png"
#define _IMAGE_JPEG "image/jpeg"
#define _IMAGE_GIF "image/gif"
#define _PNG "png"
#define _JPEG "jpeg"
#define _JS "js"
#define _CSS "css"
#define _HTML "html"
#define _ICO "ico"
#define _GIF "gif"